create or replace view v_dev_trandopdev as
select f.ocfid equip_id,
       f.ocfcode equip_code,
       f.ocfname equip_name,
       f.supname name_std,
       'ODF' equip_type,
       (select l.modelname
          from vendormodel l
         where l.vendormodelid = f.vendormodelid) model,
       (select l.vendorname from vendor l where l.vendorid = f.vendorid) vender,
       '' version,
       workdate beg_date,
       dbo.sf('ODF', 'FACSTATUS', FACSTATUS, null) status,
       '' maintain_dept,
        f.mroomid room_id,
       (select m.mroomname from com_mroom m where m.mroomid = f.mroomid) room_name,
       f.mroomid romm_id,
       (select k.devicename from com_rack k where k.rackid = f.devrackid) rack_name,
       f.devrackid rack_id,
       dbo.sf('ODF', 'MANATYPE', MANATYPE, null) disp_dept,
       to_char(MANATYPE) MANATYPE,
       null end_date,
       '' soft_version,
       '' purpose,
       '' gateway_net,
       (select n.stname from com_station n where n.sn = f.facid) station_name,
       f.facid station_id,
       f.remark remark,
       '' x,
       '' y,
       '' sys_name,
       '' qr_code,
       '' relation_id,
       'ODF' RESID
  from ocf f
 where f.restype = 'ODF'
 union all
 select h.devid equip_id,
       h.devcode equip_code,
       h.devname equip_name,
       h.supname name_std,
       'SDH设备' equip_type,
       (select l.modelname
          from vendormodel l
         where l.vendormodelid = h.vendormodelid) model,
       (select l.vendorname from vendor l where l.vendorid = h.vendorid) vender,
       '' version,
       workdate beg_date,
       dbo.sf('TR_SDH', 'FACSTATUS', FACSTATUS, null) status,
       '' maintain_dept,
        h.mroomid room_id,
       (select m.mroomname from com_mroom m where m.mroomid = h.mroomid) room_name,
       h.mroomid romm_id,
       (select k.devicename from com_rack k where k.rackid = H.devrackid) rack_name,
       H.devrackid rack_id,
       dbo.sf('TR_SDH', 'MANATYPE', MANATYPE, null) disp_dept,
       to_char(MANATYPE) MANATYPE,
       null end_date,
       '' soft_version,
       '' purpose,
       '' gateway_net,
       (select n.stname from com_station n where n.sn = h.sn) station_name,
       h.sn station_id,
       h.remark remark,
       '' x,
       '' y,
       (select s.emsname from tr_ems s where s.emsid=h.emsid) sys_name,
       '' qr_code,
       '' relation_id,
       'TR_SDH' RESID
  from tr_sdh h
  union all
  select d.ddfid equip_id,
       d.ddfcode equip_code,
       d.ddfname equip_name,
       d.supname name_std,
       'DDF设备' equip_type,
       (select l.modelname
          from vendormodel l
         where l.vendormodelid = d.ddfmodel) model,
       (select l.vendorname from vendor l where l.vendorid = d.vendorid) vender,
       '' version,
       workdate beg_date,
       dbo.sf('TR_DDF', 'FACSTATUS', FACSTATUS, null) status,
       dbo.sf('TR_DDF', 'MAINTAIN', MAINTAIN, null) maintain_dept,
        d.mroomid room_id,
       (select m.mroomname from com_mroom m where m.mroomid = d.mroomid) room_name,
       d.mroomid romm_id,
       (select k.devicename from com_rack k where k.rackid = d.devrackid) rack_name,
       d.devrackid rack_id,
       (select max(dbo.sf('COM_STATION','MANATYPE',n.manatype,null)) from com_station n where n.sn=d.sn) disp_dept,
        (select to_char(max(n.manatype)) from com_station n where n.sn=d.sn) MANATYPE,
       null end_date,
       '' soft_version,
       '' purpose,
       '' gateway_net,
       (select n.stname from com_station n where n.sn = d.sn) station_name,
       d.sn station_id,
       d.remark remark,
       '' x,
       '' y,
       '' sys_name,
       '' qr_code,
       '' relation_id,
       'TR_DDF' RESID
  from tr_ddf d;
